### ISSUE TITLE
Any kotest/pitest version combination above 5.3.2/1.8.1 crashes

### ISSUE THREAD

**Issue by SeekDaSky** [kotest/kotest-extensions-pitest#36]
Any version combination above Kotest `5.3.2` and pitest `1.8.1` crashes with `Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!`.

Here is a small reproducer, if you run the `pitest` task as is, it works, but if you try to bump the versions on line 12 or 26, the task fails.

[pitestPlusKotestBug.zip](https://github.com/kotest/kotest-extensions-pitest/files/10375087/pitestPlusKotestBug.zip)

**Comment by Kantis** [comment]
@SeekDaSky could you try using hte latest snapshot with kotest 5.5?

**Comment by SeekDaSky** [comment]
Tried it with the snapshot `1.2.0.28-SNAPSHOT` and kotest `5.5.4`. The linked reproducer is still throwing the same error sadly.

**Comment by Kantis** [comment]
The extension is now built to use Pitest 1.9+, which also removes support for Pitest 1.8 and below. Snapshot build out

**Comment by Kantis** [comment]
1.2.0 released with a fix. Please re-open the issue of it persists.

**Comment by SeekDaSky** [comment]
Confirmed that snapshot `1.2.0.30-SNAPSHOT` with pitest `1.9.0` and kotest `5.5.4` works now, thanks a lot 🎉
